%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: emsMgr_EMSMgr_I
%% Source: d:/corba/idl/emsMgr.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(EMSMGR_EMSMGR_I_HRL).
-define(EMSMGR_EMSMGR_I_HRL, true).




-endif.


