%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: emsSessionFactory_EmsSessionFactory_I
%% Source: d:/corba/idl/emsSessionFactory.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(EMSSESSIONFACTORY_EMSSESSIONFACTORY_I_HRL).
-define(EMSSESSIONFACTORY_EMSSESSIONFACTORY_I_HRL, true).




-endif.


