%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: emsSession_EmsSession_I
%% Source: d:/corba/idl/emsSession.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(EMSSESSION_EMSSESSION_I_HRL).
-define(EMSSESSION_EMSSESSION_I_HRL, true).




-endif.


