%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: nmsSession_NmsSession_I
%% Source: d:/corba/idl/nmsSession.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module(nmsSession_NmsSession_I).
-ic_compiled("4_2_25").


%% Interface functions
-export([eventLossOccurred/3, eventLossOccurred/4, eventLossCleared/2]).
-export([eventLossCleared/3]).

%% Exports from "session::Session_I"
-export(['_get_associatedSession'/1, '_get_associatedSession'/2, ping/1]).
-export([ping/2, endSession/1, endSession/2]).

%% Type identification function
-export([typeID/0]).

%% Used to start server
-export([oe_create/0, oe_create_link/0, oe_create/1]).
-export([oe_create_link/1, oe_create/2, oe_create_link/2]).

%% TypeCode Functions and inheritance
-export([oe_tc/1, oe_is_a/1, oe_get_interface/0]).

%% gen server export stuff
-behaviour(gen_server).
-export([init/1, terminate/2, handle_call/3]).
-export([handle_cast/2, handle_info/2, code_change/3]).

-include_lib("orber/include/corba.hrl").


%%------------------------------------------------------------
%%
%% Object interface functions.
%%
%%------------------------------------------------------------



%%%% Operation: eventLossOccurred
%% 
%%   Returns: RetVal
%%
eventLossOccurred(OE_THIS, StartTime, NotificationId) ->
    corba:call(OE_THIS, eventLossOccurred, [StartTime, NotificationId], ?MODULE).

eventLossOccurred(OE_THIS, OE_Options, StartTime, NotificationId) ->
    corba:call(OE_THIS, eventLossOccurred, [StartTime, NotificationId], ?MODULE, OE_Options).

%%%% Operation: eventLossCleared
%% 
%%   Returns: RetVal
%%
eventLossCleared(OE_THIS, EndTime) ->
    corba:call(OE_THIS, eventLossCleared, [EndTime], ?MODULE).

eventLossCleared(OE_THIS, OE_Options, EndTime) ->
    corba:call(OE_THIS, eventLossCleared, [EndTime], ?MODULE, OE_Options).

%%%% Operation: '_get_associatedSession'
%% 
%%   Returns: RetVal
%%
'_get_associatedSession'(OE_THIS) ->
    corba:call(OE_THIS, '_get_associatedSession', [], ?MODULE).

'_get_associatedSession'(OE_THIS, OE_Options) ->
    corba:call(OE_THIS, '_get_associatedSession', [], ?MODULE, OE_Options).

%%%% Operation: ping
%% 
%%   Returns: RetVal
%%
ping(OE_THIS) ->
    corba:call(OE_THIS, ping, [], ?MODULE).

ping(OE_THIS, OE_Options) ->
    corba:call(OE_THIS, ping, [], ?MODULE, OE_Options).

%%%% Operation: endSession
%% 
%%   Returns: RetVal
%%
endSession(OE_THIS) ->
    corba:cast(OE_THIS, endSession, [], ?MODULE).

endSession(OE_THIS, OE_Options) ->
    corba:cast(OE_THIS, endSession, [], ?MODULE, OE_Options).

%%------------------------------------------------------------
%%
%% Inherited Interfaces
%%
%%------------------------------------------------------------
oe_is_a("IDL:mtnm.tmforum.org/nmsSession/NmsSession_I:1.0") -> true;
oe_is_a("IDL:mtnm.tmforum.org/session/Session_I:1.0") -> true;
oe_is_a(_) -> false.

%%------------------------------------------------------------
%%
%% Interface TypeCode
%%
%%------------------------------------------------------------
oe_tc(eventLossOccurred) -> 
	{tk_void,[{tk_string,0},{tk_string,0}],[]};
oe_tc(eventLossCleared) -> 
	{tk_void,[{tk_string,0}],[]};
oe_tc('_get_associatedSession') -> session_Session_I:oe_tc('_get_associatedSession');
oe_tc(ping) -> session_Session_I:oe_tc(ping);
oe_tc(endSession) -> session_Session_I:oe_tc(endSession);
oe_tc(_) -> undefined.

oe_get_interface() -> 
	[{"endSession", session_Session_I:oe_tc(endSession)},
	{"ping", session_Session_I:oe_tc(ping)},
	{"_get_associatedSession", session_Session_I:oe_tc('_get_associatedSession')},
	{"eventLossCleared", oe_tc(eventLossCleared)},
	{"eventLossOccurred", oe_tc(eventLossOccurred)}].




%%------------------------------------------------------------
%%
%% Object server implementation.
%%
%%------------------------------------------------------------


%%------------------------------------------------------------
%%
%% Function for fetching the interface type ID.
%%
%%------------------------------------------------------------

typeID() ->
    "IDL:mtnm.tmforum.org/nmsSession/NmsSession_I:1.0".


%%------------------------------------------------------------
%%
%% Object creation functions.
%%
%%------------------------------------------------------------

oe_create() ->
    corba:create(?MODULE, "IDL:mtnm.tmforum.org/nmsSession/NmsSession_I:1.0").

oe_create_link() ->
    corba:create_link(?MODULE, "IDL:mtnm.tmforum.org/nmsSession/NmsSession_I:1.0").

oe_create(Env) ->
    corba:create(?MODULE, "IDL:mtnm.tmforum.org/nmsSession/NmsSession_I:1.0", Env).

oe_create_link(Env) ->
    corba:create_link(?MODULE, "IDL:mtnm.tmforum.org/nmsSession/NmsSession_I:1.0", Env).

oe_create(Env, RegName) ->
    corba:create(?MODULE, "IDL:mtnm.tmforum.org/nmsSession/NmsSession_I:1.0", Env, RegName).

oe_create_link(Env, RegName) ->
    corba:create_link(?MODULE, "IDL:mtnm.tmforum.org/nmsSession/NmsSession_I:1.0", Env, RegName).

%%------------------------------------------------------------
%%
%% Init & terminate functions.
%%
%%------------------------------------------------------------

init(Env) ->
%% Call to implementation init
    corba:handle_init(nmsSession_NmsSession_I_impl, Env).

terminate(Reason, State) ->
    corba:handle_terminate(nmsSession_NmsSession_I_impl, Reason, State).


%%%% Operation: eventLossOccurred
%% 
%%   Returns: RetVal
%%
handle_call({_, OE_Context, eventLossOccurred, [StartTime, NotificationId]}, _, OE_State) ->
  corba:handle_call(nmsSession_NmsSession_I_impl, eventLossOccurred, [StartTime, NotificationId], OE_State, OE_Context, false, false);

%%%% Operation: eventLossCleared
%% 
%%   Returns: RetVal
%%
handle_call({_, OE_Context, eventLossCleared, [EndTime]}, _, OE_State) ->
  corba:handle_call(nmsSession_NmsSession_I_impl, eventLossCleared, [EndTime], OE_State, OE_Context, false, false);

%%%% Operation: '_get_associatedSession'
%% 
%%   Returns: RetVal
%%
handle_call({_, OE_Context, '_get_associatedSession', []}, _, OE_State) ->
  corba:handle_call(nmsSession_NmsSession_I_impl, '_get_associatedSession', [], OE_State, OE_Context, false, false);

%%%% Operation: ping
%% 
%%   Returns: RetVal
%%
handle_call({_, _OE_Context, ping, []}, _, OE_State) ->
  %~ io:format("___________________________~n~n~n OE_Context: ~p~n~n~n",[{OE_Context,OE_State}]),
  State = case OE_State of
	{{is,I},[]} -> {{is,I + 1},[]};
	_ -> OE_State
  end,
  {reply, ok,State};
  %~ corba:handle_call(nmsSession_NmsSession_I_impl, ping, [], OE_State, OE_Context, false, false);



%%%% Standard gen_server call handle
%%
handle_call(stop, _, State) ->
    {stop, normal, ok, State};

handle_call(_, _, State) ->
    {reply, catch corba:raise(#'BAD_OPERATION'{minor=1163001857, completion_status='COMPLETED_NO'}), State}.
%%%% Operation: endSession
%% 
%%   Returns: RetVal
%%
handle_cast({_, OE_Context, endSession, []}, OE_State) ->
    corba:handle_cast(nmsSession_NmsSession_I_impl, endSession, [], OE_State, OE_Context, false);



%%%% Standard gen_server cast handle
%%
handle_cast(stop, State) ->
    {stop, normal, State};

handle_cast(_, State) ->
    {noreply, State}.


%%%% Standard gen_server handles
%%
handle_info(_, State) ->
    {noreply, State}.


code_change(OldVsn, State, Extra) ->
    corba:handle_code_change(nmsSession_NmsSession_I_impl, OldVsn, State, Extra).

