%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: nmsSession_NmsSession_I
%% Source: d:/corba/idl/nmsSession.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(NMSSESSION_NMSSESSION_I_HRL).
-define(NMSSESSION_NMSSESSION_I_HRL, true).




-endif.


