%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: notifications_EventIterator_I
%% Source: d:/corba/idl/notifications.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(NOTIFICATIONS_EVENTITERATOR_I_HRL).
-define(NOTIFICATIONS_EVENTITERATOR_I_HRL, true).




-endif.


