%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_common
%% Source: d:/corba/idl/common.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COMMON_HRL).
-define(OE_COMMON_HRL, true).




-endif.


