%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_emsMgr
%% Source: d:/corba/idl/emsMgr.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_EMSMGR_HRL).
-define(OE_EMSMGR_HRL, true).




-endif.


