%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_globaldefs
%% Source: d:/corba/idl/globaldefs.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_GLOBALDEFS_HRL).
-define(OE_GLOBALDEFS_HRL, true).




-endif.


