%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: oe_globaldefs
%% Source: d:/corba/idl/globaldefs.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module(oe_globaldefs).
-ic_compiled("4_2_25").


-include_lib("orber/include/ifr_types.hrl").

%% Interface functions

-export([oe_register/0, oe_unregister/0, oe_get_module/5]).
-export([oe_dependency/0]).



oe_register() ->
    OE_IFR = orber_ifr:find_repository(),

    register_tests(OE_IFR),

    _OE_1 = oe_get_top_module(OE_IFR, "IDL:mtnm.tmforum.org/globaldefs:1.0", "globaldefs", "1.0"),

    orber_ifr:'ModuleDef_create_struct'(_OE_1, "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0", "NameAndStringValue_T", "1.0", [#structmember{name="name", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0})}, #structmember{name="value", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0})}]),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0", "NVSList_T", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                "NameAndStringValue_T",
                                                [{"name",{tk_string,0}},
                                                 {"value",{tk_string,0}}]},
                                               0})),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0", "NamingAttributes_T", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                "NameAndStringValue_T",
                                                [{"name",{tk_string,0}},
                                                 {"value",{tk_string,0}}]},
                                               0})),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:mtnm.tmforum.org/globaldefs/NamingAttributesList_T:1.0", "NamingAttributesList_T", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_sequence,
                                                {tk_struct,
                                                 "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                 "NameAndStringValue_T",
                                                 [{"name",{tk_string,0}},
                                                  {"value",{tk_string,0}}]},
                                                0},
                                               0})),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:mtnm.tmforum.org/globaldefs/Time_T:1.0", "Time_T", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0})),

    orber_ifr:'ModuleDef_create_enum'(_OE_1, "IDL:mtnm.tmforum.org/globaldefs/ConnectionDirection_T:1.0", "ConnectionDirection_T", "1.0", ["CD_UNI","CD_BI"]),

    orber_ifr:'ModuleDef_create_enum'(_OE_1, "IDL:mtnm.tmforum.org/globaldefs/ExceptionType_T:1.0", "ExceptionType_T", "1.0", ["EXCPT_NOT_IMPLEMENTED","EXCPT_INTERNAL_ERROR","EXCPT_INVALID_INPUT",
   "EXCPT_OBJECT_IN_USE","EXCPT_TP_INVALID_ENDPOINT","EXCPT_ENTITY_NOT_FOUND",
   "EXCPT_TIMESLOT_IN_USE","EXCPT_PROTECTION_EFFORT_NOT_MET",
   "EXCPT_NOT_IN_VALID_STATE","EXCPT_UNABLE_TO_COMPLY","EXCPT_NE_COMM_LOSS",
   "EXCPT_CAPACITY_EXCEEDED","EXCPT_ACCESS_DENIED",
   "EXCPT_TOO_MANY_OPEN_ITERATORS","EXCPT_UNSUPPORTED_ROUTING_CONSTRAINTS",
   "EXCPT_USERLABEL_IN_USE"]),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:mtnm.tmforum.org/globaldefs/ProcessingFailureException:1.0", "ProcessingFailureException", "1.0", [#structmember{name="exceptionType", type={tk_enum,
                                          "IDL:mtnm.tmforum.org/globaldefs/ExceptionType_T:1.0",
                                          "ExceptionType_T",
                                          ["EXCPT_NOT_IMPLEMENTED",
                                           "EXCPT_INTERNAL_ERROR",
                                           "EXCPT_INVALID_INPUT",
                                           "EXCPT_OBJECT_IN_USE",
                                           "EXCPT_TP_INVALID_ENDPOINT",
                                           "EXCPT_ENTITY_NOT_FOUND",
                                           "EXCPT_TIMESLOT_IN_USE",
                                           "EXCPT_PROTECTION_EFFORT_NOT_MET",
                                           "EXCPT_NOT_IN_VALID_STATE",
                                           "EXCPT_UNABLE_TO_COMPLY",
                                           "EXCPT_NE_COMM_LOSS",
                                           "EXCPT_CAPACITY_EXCEEDED",
                                           "EXCPT_ACCESS_DENIED",
                                           "EXCPT_TOO_MANY_OPEN_ITERATORS",
                                           "EXCPT_UNSUPPORTED_ROUTING_CONSTRAINTS",
                                           "EXCPT_USERLABEL_IN_USE"]}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_enum,
                                               "IDL:mtnm.tmforum.org/globaldefs/ExceptionType_T:1.0",
                                               "ExceptionType_T",
                                               ["EXCPT_NOT_IMPLEMENTED",
                                                "EXCPT_INTERNAL_ERROR",
                                                "EXCPT_INVALID_INPUT",
                                                "EXCPT_OBJECT_IN_USE",
                                                "EXCPT_TP_INVALID_ENDPOINT",
                                                "EXCPT_ENTITY_NOT_FOUND",
                                                "EXCPT_TIMESLOT_IN_USE",
                                                "EXCPT_PROTECTION_EFFORT_NOT_MET",
                                                "EXCPT_NOT_IN_VALID_STATE",
                                                "EXCPT_UNABLE_TO_COMPLY",
                                                "EXCPT_NE_COMM_LOSS",
                                                "EXCPT_CAPACITY_EXCEEDED",
                                                "EXCPT_ACCESS_DENIED",
                                                "EXCPT_TOO_MANY_OPEN_ITERATORS",
                                                "EXCPT_UNSUPPORTED_ROUTING_CONSTRAINTS",
                                                "EXCPT_USERLABEL_IN_USE"]})}, #structmember{name="errorReason", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0})}]),

    _OE_2 = orber_ifr:'ModuleDef_create_interface'(_OE_1, "IDL:mtnm.tmforum.org/globaldefs/NamingAttributesIterator_I:1.0", "NamingAttributesIterator_I", "1.0", []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_2, "IDL:mtnm.tmforum.org/globaldefs/NamingAttributesIterator_I/next_n:1.0", "next_n", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_boolean), 'OP_NORMAL', [#parameterdescription{name="nameList", type={tk_sequence,
                                             {tk_sequence,
                                              {tk_struct,
                                               "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                               "NameAndStringValue_T",
                                               [{"name",{tk_string,0}},
                                                {"value",{tk_string,0}}]},
                                              0},
                                             0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_sequence,
                                                {tk_struct,
                                                 "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                 "NameAndStringValue_T",
                                                 [{"name",{tk_string,0}},
                                                  {"value",{tk_string,0}}]},
                                                0},
                                               0}), mode='PARAM_OUT'}
, #parameterdescription{name="how_many", type=tk_ulong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:mtnm.tmforum.org/globaldefs/ProcessingFailureException:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_2, "IDL:mtnm.tmforum.org/globaldefs/NamingAttributesIterator_I/getLength:1.0", "getLength", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), 'OP_NORMAL', [], [orber_ifr:lookup_id(OE_IFR,"IDL:mtnm.tmforum.org/globaldefs/ProcessingFailureException:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_2, "IDL:mtnm.tmforum.org/globaldefs/NamingAttributesIterator_I/destroy:1.0", "destroy", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [], [orber_ifr:lookup_id(OE_IFR,"IDL:mtnm.tmforum.org/globaldefs/ProcessingFailureException:1.0")], []),

    ok.


%% General IFR registration checks.
register_tests(OE_IFR)->
  re_register_test(OE_IFR),
  include_reg_test(OE_IFR).


%% IFR type Re-registration checks.
re_register_test(OE_IFR)->
  case orber_ifr:'Repository_lookup_id'(OE_IFR,"IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0") of
    []  ->
      true;
    _ ->
      exit({allready_registered,"IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0"})
 end.


%% No included idl-files detected.
include_reg_test(_OE_IFR) -> true.


%% Fetch top module reference, register if unregistered.
oe_get_top_module(OE_IFR, ID, Name, Version) ->
  case orber_ifr:'Repository_lookup_id'(OE_IFR, ID) of
    [] ->
      orber_ifr:'Repository_create_module'(OE_IFR, ID, Name, Version);
    Mod  ->
      Mod
   end.

%% Fetch module reference, register if unregistered.
oe_get_module(OE_IFR, OE_Parent, ID, Name, Version) ->
  case orber_ifr:'Repository_lookup_id'(OE_IFR, ID) of
    [] ->
      orber_ifr:'ModuleDef_create_module'(OE_Parent, ID, Name, Version);
    Mod  ->
      Mod
   end.



oe_unregister() ->
    OE_IFR = orber_ifr:find_repository(),

    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/globaldefs/NamingAttributesIterator_I:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/globaldefs/ProcessingFailureException:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/globaldefs/ExceptionType_T:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/globaldefs/ConnectionDirection_T:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/globaldefs/Time_T:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/globaldefs/NamingAttributesList_T:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0"),
    oe_destroy_if_empty(OE_IFR, "IDL:mtnm.tmforum.org/globaldefs:1.0"),
    ok.


oe_destroy_if_empty(OE_IFR,IFR_ID) ->
    case orber_ifr:'Repository_lookup_id'(OE_IFR, IFR_ID) of
	[] ->
	    ok;
	Ref ->
	    case orber_ifr:contents(Ref, 'dk_All', 'true') of
		[] ->
		    orber_ifr:destroy(Ref),
		    ok;
		_ ->
		    ok
	    end
    end.

oe_destroy(OE_IFR,IFR_ID) ->
    case orber_ifr:'Repository_lookup_id'(OE_IFR, IFR_ID) of
	[] ->
	    ok;
	Ref ->
	    orber_ifr:destroy(Ref),
	    ok
    end.



%% Idl file dependency list function
oe_dependency() ->

    [].

