%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_managedElement
%% Source: d:/corba/idl/managedElement.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_MANAGEDELEMENT_HRL).
-define(OE_MANAGEDELEMENT_HRL, true).




-endif.


