%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_multiLayerSubnetwork
%% Source: d:/corba/idl/multiLayerSubnetwork.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_MULTILAYERSUBNETWORK_HRL).
-define(OE_MULTILAYERSUBNETWORK_HRL, true).




-endif.


