%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_notifications
%% Source: d:/corba/idl/notifications.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_NOTIFICATIONS_HRL).
-define(OE_NOTIFICATIONS_HRL, true).




-endif.


