%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_protection
%% Source: d:/corba/idl/protection.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_PROTECTION_HRL).
-define(OE_PROTECTION_HRL, true).




-endif.


