%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_subnetworkConnection
%% Source: d:/corba/idl/subnetworkConnection.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_SUBNETWORKCONNECTION_HRL).
-define(OE_SUBNETWORKCONNECTION_HRL, true).




-endif.


