%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: oe_transmissionParameters
%% Source: d:/corba/idl/transmissionParameters.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module(oe_transmissionParameters).
-ic_compiled("4_2_25").


-include_lib("orber/include/ifr_types.hrl").

%% Interface functions

-export([oe_register/0, oe_unregister/0, oe_get_module/5]).
-export([oe_dependency/0]).



oe_register() ->
    OE_IFR = orber_ifr:find_repository(),

    register_tests(OE_IFR),

    _OE_1 = oe_get_top_module(OE_IFR, "IDL:mtnm.tmforum.org/transmissionParameters:1.0", "transmissionParameters", "1.0"),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:mtnm.tmforum.org/transmissionParameters/LayerRate_T:1.0", "LayerRate_T", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_short)),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:mtnm.tmforum.org/transmissionParameters/LayerRateList_T:1.0", "LayerRateList_T", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,tk_short,0})),

    orber_ifr:'ModuleDef_create_struct'(_OE_1, "IDL:mtnm.tmforum.org/transmissionParameters/LayeredParameters_T:1.0", "LayeredParameters_T", "1.0", [#structmember{name="layer", type=tk_short, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_short)}, #structmember{name="transmissionParams", type={tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                "NameAndStringValue_T",
                                                [{"name",{tk_string,0}},
                                                 {"value",{tk_string,0}}]},
                                               0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                "NameAndStringValue_T",
                                                [{"name",{tk_string,0}},
                                                 {"value",{tk_string,0}}]},
                                               0})}]),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:mtnm.tmforum.org/transmissionParameters/LayeredParameterList_T:1.0", "LayeredParameterList_T", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/transmissionParameters/LayeredParameters_T:1.0",
                                                "LayeredParameters_T",
                                                [{"layer",tk_short},
                                                 {"transmissionParams",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                    "NameAndStringValue_T",
                                                    [{"name",{tk_string,0}},
                                                     {"value",{tk_string,0}}]},
                                                   0}}]},
                                               0})),

    ok.


%% General IFR registration checks.
register_tests(OE_IFR)->
  re_register_test(OE_IFR),
  include_reg_test(OE_IFR).


%% IFR type Re-registration checks.
re_register_test(OE_IFR)->
  case orber_ifr:'Repository_lookup_id'(OE_IFR,"IDL:mtnm.tmforum.org/transmissionParameters/LayerRate_T:1.0") of
    []  ->
      true;
    _ ->
      exit({allready_registered,"IDL:mtnm.tmforum.org/transmissionParameters/LayerRate_T:1.0"})
 end.


%% IFR registration checks for included idl files.
include_reg_test(OE_IFR) ->
  case orber_ifr:'Repository_lookup_id'(OE_IFR,"IDL:mtnm.tmforum.org/globaldefs:1.0") of
    [] ->
      exit({unregistered,"IDL:mtnm.tmforum.org/globaldefs:1.0"});
    _  ->
      true
  end,
  true.


%% Fetch top module reference, register if unregistered.
oe_get_top_module(OE_IFR, ID, Name, Version) ->
  case orber_ifr:'Repository_lookup_id'(OE_IFR, ID) of
    [] ->
      orber_ifr:'Repository_create_module'(OE_IFR, ID, Name, Version);
    Mod  ->
      Mod
   end.

%% Fetch module reference, register if unregistered.
oe_get_module(OE_IFR, OE_Parent, ID, Name, Version) ->
  case orber_ifr:'Repository_lookup_id'(OE_IFR, ID) of
    [] ->
      orber_ifr:'ModuleDef_create_module'(OE_Parent, ID, Name, Version);
    Mod  ->
      Mod
   end.



oe_unregister() ->
    OE_IFR = orber_ifr:find_repository(),

    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/transmissionParameters/LayeredParameterList_T:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/transmissionParameters/LayeredParameters_T:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/transmissionParameters/LayerRateList_T:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/transmissionParameters/LayerRate_T:1.0"),
    oe_destroy_if_empty(OE_IFR, "IDL:mtnm.tmforum.org/transmissionParameters:1.0"),
    ok.


oe_destroy_if_empty(OE_IFR,IFR_ID) ->
    case orber_ifr:'Repository_lookup_id'(OE_IFR, IFR_ID) of
	[] ->
	    ok;
	Ref ->
	    case orber_ifr:contents(Ref, 'dk_All', 'true') of
		[] ->
		    orber_ifr:destroy(Ref),
		    ok;
		_ ->
		    ok
	    end
    end.

oe_destroy(OE_IFR,IFR_ID) ->
    case orber_ifr:'Repository_lookup_id'(OE_IFR, IFR_ID) of
	[] ->
	    ok;
	Ref ->
	    orber_ifr:destroy(Ref),
	    ok
    end.



%% Idl file dependency list function
oe_dependency() ->

    {"d:/corba/idl/transmissionParameters.idl",["globaldefs.idl"]}.

