%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_topologicalLink
%% Source: d:/corba/idl/topologicalLink.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_TOPOLOGICALLINK_HRL).
-define(OE_TOPOLOGICALLINK_HRL, true).




-endif.


