%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_terminationPoint
%% Source: d:/corba/idl/terminationPoint.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_TERMINATIONPOINT_HRL).
-define(OE_TERMINATIONPOINT_HRL, true).




-endif.


