%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_transmissionParameters
%% Source: d:/corba/idl/transmissionParameters.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_TRANSMISSIONPARAMETERS_HRL).
-define(OE_TRANSMISSIONPARAMETERS_HRL, true).




-endif.


