%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: oe_terminationPoint
%% Source: d:/corba/idl/terminationPoint.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module(oe_terminationPoint).
-ic_compiled("4_2_25").


-include_lib("orber/include/ifr_types.hrl").

%% Interface functions

-export([oe_register/0, oe_unregister/0, oe_get_module/5]).
-export([oe_dependency/0]).



oe_register() ->
    OE_IFR = orber_ifr:find_repository(),

    register_tests(OE_IFR),

    _OE_1 = oe_get_top_module(OE_IFR, "IDL:mtnm.tmforum.org/terminationPoint:1.0", "terminationPoint", "1.0"),

    orber_ifr:'ModuleDef_create_enum'(_OE_1, "IDL:mtnm.tmforum.org/terminationPoint/Directionality_T:1.0", "Directionality_T", "1.0", ["D_NA","D_BIDIRECTIONAL","D_SOURCE","D_SINK"]),

    orber_ifr:'ModuleDef_create_enum'(_OE_1, "IDL:mtnm.tmforum.org/terminationPoint/TPConnectionState_T:1.0", "TPConnectionState_T", "1.0", ["TPCS_NA","TPCS_SOURCE_CONNECTED","TPCS_SINK_CONNECTED",
   "TPCS_BI_CONNECTED","TPCS_NOT_CONNECTED"]),

    orber_ifr:'ModuleDef_create_enum'(_OE_1, "IDL:mtnm.tmforum.org/terminationPoint/TPType_T:1.0", "TPType_T", "1.0", ["TPT_PTP","TPT_CTP","TPT_TPPool"]),

    orber_ifr:'ModuleDef_create_enum'(_OE_1, "IDL:mtnm.tmforum.org/terminationPoint/TerminationMode_T:1.0", "TerminationMode_T", "1.0", ["TM_NA","TM_NEITHER_TERMINATED_NOR_AVAILABLE_FOR_MAPPING",
   "TM_TERMINATED_AND_AVAILABLE_FOR_MAPPING"]),

    orber_ifr:'ModuleDef_create_enum'(_OE_1, "IDL:mtnm.tmforum.org/terminationPoint/TPProtectionAssociation_T:1.0", "TPProtectionAssociation_T", "1.0", ["TPPA_NA","TPPA_PSR_RELATED"]),

    orber_ifr:'ModuleDef_create_struct'(_OE_1, "IDL:mtnm.tmforum.org/terminationPoint/TerminationPoint_T:1.0", "TerminationPoint_T", "1.0", [#structmember{name="name", type={tk_sequence,
                                 {tk_struct,
                                  "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                  "NameAndStringValue_T",
                                  [{"name",{tk_string,0}},
                                   {"value",{tk_string,0}}]},
                                 0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                "NameAndStringValue_T",
                                                [{"name",{tk_string,0}},
                                                 {"value",{tk_string,0}}]},
                                               0})}, #structmember{name="userLabel", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0})}, #structmember{name="nativeEMSName", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0})}, #structmember{name="owner", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0})}, #structmember{name="ingressTrafficDescriptorName", type={tk_sequence,
                                                         {tk_struct,
                                                          "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                          "NameAndStringValue_T",
                                                          [{"name",
                                                            {tk_string,0}},
                                                           {"value",
                                                            {tk_string,0}}]},
                                                         0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                "NameAndStringValue_T",
                                                [{"name",{tk_string,0}},
                                                 {"value",{tk_string,0}}]},
                                               0})}, #structmember{name="egressTrafficDescriptorName", type={tk_sequence,
                                                        {tk_struct,
                                                         "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                         "NameAndStringValue_T",
                                                         [{"name",
                                                           {tk_string,0}},
                                                          {"value",
                                                           {tk_string,0}}]},
                                                        0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                "NameAndStringValue_T",
                                                [{"name",{tk_string,0}},
                                                 {"value",{tk_string,0}}]},
                                               0})}, #structmember{name="type", type={tk_enum,
                                    "IDL:mtnm.tmforum.org/terminationPoint/TPType_T:1.0",
                                    "TPType_T",
                                    ["TPT_PTP","TPT_CTP","TPT_TPPool"]}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_enum,
                                               "IDL:mtnm.tmforum.org/terminationPoint/TPType_T:1.0",
                                               "TPType_T",
                                               ["TPT_PTP","TPT_CTP",
                                                "TPT_TPPool"]})}, #structmember{name="connectionState", type={tk_enum,
                                            "IDL:mtnm.tmforum.org/terminationPoint/TPConnectionState_T:1.0",
                                            "TPConnectionState_T",
                                            ["TPCS_NA",
                                             "TPCS_SOURCE_CONNECTED",
                                             "TPCS_SINK_CONNECTED",
                                             "TPCS_BI_CONNECTED",
                                             "TPCS_NOT_CONNECTED"]}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_enum,
                                               "IDL:mtnm.tmforum.org/terminationPoint/TPConnectionState_T:1.0",
                                               "TPConnectionState_T",
                                               ["TPCS_NA",
                                                "TPCS_SOURCE_CONNECTED",
                                                "TPCS_SINK_CONNECTED",
                                                "TPCS_BI_CONNECTED",
                                                "TPCS_NOT_CONNECTED"]})}, #structmember{name="tpMappingMode", type={tk_enum,
                                          "IDL:mtnm.tmforum.org/terminationPoint/TerminationMode_T:1.0",
                                          "TerminationMode_T",
                                          ["TM_NA",
                                           "TM_NEITHER_TERMINATED_NOR_AVAILABLE_FOR_MAPPING",
                                           "TM_TERMINATED_AND_AVAILABLE_FOR_MAPPING"]}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_enum,
                                               "IDL:mtnm.tmforum.org/terminationPoint/TerminationMode_T:1.0",
                                               "TerminationMode_T",
                                               ["TM_NA",
                                                "TM_NEITHER_TERMINATED_NOR_AVAILABLE_FOR_MAPPING",
                                                "TM_TERMINATED_AND_AVAILABLE_FOR_MAPPING"]})}, #structmember{name="direction", type={tk_enum,
                                      "IDL:mtnm.tmforum.org/terminationPoint/Directionality_T:1.0",
                                      "Directionality_T",
                                      ["D_NA","D_BIDIRECTIONAL","D_SOURCE",
                                       "D_SINK"]}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_enum,
                                               "IDL:mtnm.tmforum.org/terminationPoint/Directionality_T:1.0",
                                               "Directionality_T",
                                               ["D_NA","D_BIDIRECTIONAL",
                                                "D_SOURCE","D_SINK"]})}, #structmember{name="transmissionParams", type={tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/transmissionParameters/LayeredParameters_T:1.0",
                                                "LayeredParameters_T",
                                                [{"layer",tk_short},
                                                 {"transmissionParams",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                    "NameAndStringValue_T",
                                                    [{"name",{tk_string,0}},
                                                     {"value",{tk_string,0}}]},
                                                   0}}]},
                                               0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/transmissionParameters/LayeredParameters_T:1.0",
                                                "LayeredParameters_T",
                                                [{"layer",tk_short},
                                                 {"transmissionParams",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                    "NameAndStringValue_T",
                                                    [{"name",{tk_string,0}},
                                                     {"value",{tk_string,0}}]},
                                                   0}}]},
                                               0})}, #structmember{name="tpProtectionAssociation", type={tk_enum,
                                                    "IDL:mtnm.tmforum.org/terminationPoint/TPProtectionAssociation_T:1.0",
                                                    "TPProtectionAssociation_T",
                                                    ["TPPA_NA",
                                                     "TPPA_PSR_RELATED"]}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_enum,
                                               "IDL:mtnm.tmforum.org/terminationPoint/TPProtectionAssociation_T:1.0",
                                               "TPProtectionAssociation_T",
                                               ["TPPA_NA","TPPA_PSR_RELATED"]})}, #structmember{name="edgePoint", type=tk_boolean, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_boolean)}, #structmember{name="additionalInfo", type={tk_sequence,
                                           {tk_struct,
                                            "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                            "NameAndStringValue_T",
                                            [{"name",{tk_string,0}},
                                             {"value",{tk_string,0}}]},
                                           0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                "NameAndStringValue_T",
                                                [{"name",{tk_string,0}},
                                                 {"value",{tk_string,0}}]},
                                               0})}]),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:mtnm.tmforum.org/terminationPoint/TerminationPointList_T:1.0", "TerminationPointList_T", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/terminationPoint/TerminationPoint_T:1.0",
                                                "TerminationPoint_T",
                                                [{"name",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                    "NameAndStringValue_T",
                                                    [{"name",{tk_string,0}},
                                                     {"value",{tk_string,0}}]},
                                                   0}},
                                                 {"userLabel",{tk_string,0}},
                                                 {"nativeEMSName",
                                                  {tk_string,0}},
                                                 {"owner",{tk_string,0}},
                                                 {"ingressTrafficDescriptorName",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                    "NameAndStringValue_T",
                                                    [{"name",{tk_string,0}},
                                                     {"value",{tk_string,0}}]},
                                                   0}},
                                                 {"egressTrafficDescriptorName",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                    "NameAndStringValue_T",
                                                    [{"name",{tk_string,0}},
                                                     {"value",{tk_string,0}}]},
                                                   0}},
                                                 {"type",
                                                  {tk_enum,
                                                   "IDL:mtnm.tmforum.org/terminationPoint/TPType_T:1.0",
                                                   "TPType_T",
                                                   ["TPT_PTP","TPT_CTP",
                                                    "TPT_TPPool"]}},
                                                 {"connectionState",
                                                  {tk_enum,
                                                   "IDL:mtnm.tmforum.org/terminationPoint/TPConnectionState_T:1.0",
                                                   "TPConnectionState_T",
                                                   ["TPCS_NA",
                                                    "TPCS_SOURCE_CONNECTED",
                                                    "TPCS_SINK_CONNECTED",
                                                    "TPCS_BI_CONNECTED",
                                                    "TPCS_NOT_CONNECTED"]}},
                                                 {"tpMappingMode",
                                                  {tk_enum,
                                                   "IDL:mtnm.tmforum.org/terminationPoint/TerminationMode_T:1.0",
                                                   "TerminationMode_T",
                                                   ["TM_NA",
                                                    "TM_NEITHER_TERMINATED_NOR_AVAILABLE_FOR_MAPPING",
                                                    "TM_TERMINATED_AND_AVAILABLE_FOR_MAPPING"]}},
                                                 {"direction",
                                                  {tk_enum,
                                                   "IDL:mtnm.tmforum.org/terminationPoint/Directionality_T:1.0",
                                                   "Directionality_T",
                                                   ["D_NA","D_BIDIRECTIONAL",
                                                    "D_SOURCE","D_SINK"]}},
                                                 {"transmissionParams",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:mtnm.tmforum.org/transmissionParameters/LayeredParameters_T:1.0",
                                                    "LayeredParameters_T",
                                                    [{"layer",tk_short},
                                                     {"transmissionParams",
                                                      {tk_sequence,
                                                       {tk_struct,
                                                        "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                        "NameAndStringValue_T",
                                                        [{"name",
                                                          {tk_string,0}},
                                                         {"value",
                                                          {tk_string,0}}]},
                                                       0}}]},
                                                   0}},
                                                 {"tpProtectionAssociation",
                                                  {tk_enum,
                                                   "IDL:mtnm.tmforum.org/terminationPoint/TPProtectionAssociation_T:1.0",
                                                   "TPProtectionAssociation_T",
                                                   ["TPPA_NA",
                                                    "TPPA_PSR_RELATED"]}},
                                                 {"edgePoint",tk_boolean},
                                                 {"additionalInfo",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                    "NameAndStringValue_T",
                                                    [{"name",{tk_string,0}},
                                                     {"value",{tk_string,0}}]},
                                                   0}}]},
                                               0})),

    _OE_2 = orber_ifr:'ModuleDef_create_interface'(_OE_1, "IDL:mtnm.tmforum.org/terminationPoint/TerminationPointIterator_I:1.0", "TerminationPointIterator_I", "1.0", []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_2, "IDL:mtnm.tmforum.org/terminationPoint/TerminationPointIterator_I/next_n:1.0", "next_n", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_boolean), 'OP_NORMAL', [#parameterdescription{name="tpList", type={tk_sequence,
                                           {tk_struct,
                                            "IDL:mtnm.tmforum.org/terminationPoint/TerminationPoint_T:1.0",
                                            "TerminationPoint_T",
                                            [{"name",
                                              {tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                "NameAndStringValue_T",
                                                [{"name",{tk_string,0}},
                                                 {"value",{tk_string,0}}]},
                                               0}},
                                             {"userLabel",{tk_string,0}},
                                             {"nativeEMSName",{tk_string,0}},
                                             {"owner",{tk_string,0}},
                                             {"ingressTrafficDescriptorName",
                                              {tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                "NameAndStringValue_T",
                                                [{"name",{tk_string,0}},
                                                 {"value",{tk_string,0}}]},
                                               0}},
                                             {"egressTrafficDescriptorName",
                                              {tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                "NameAndStringValue_T",
                                                [{"name",{tk_string,0}},
                                                 {"value",{tk_string,0}}]},
                                               0}},
                                             {"type",
                                              {tk_enum,
                                               "IDL:mtnm.tmforum.org/terminationPoint/TPType_T:1.0",
                                               "TPType_T",
                                               ["TPT_PTP","TPT_CTP",
                                                "TPT_TPPool"]}},
                                             {"connectionState",
                                              {tk_enum,
                                               "IDL:mtnm.tmforum.org/terminationPoint/TPConnectionState_T:1.0",
                                               "TPConnectionState_T",
                                               ["TPCS_NA",
                                                "TPCS_SOURCE_CONNECTED",
                                                "TPCS_SINK_CONNECTED",
                                                "TPCS_BI_CONNECTED",
                                                "TPCS_NOT_CONNECTED"]}},
                                             {"tpMappingMode",
                                              {tk_enum,
                                               "IDL:mtnm.tmforum.org/terminationPoint/TerminationMode_T:1.0",
                                               "TerminationMode_T",
                                               ["TM_NA",
                                                "TM_NEITHER_TERMINATED_NOR_AVAILABLE_FOR_MAPPING",
                                                "TM_TERMINATED_AND_AVAILABLE_FOR_MAPPING"]}},
                                             {"direction",
                                              {tk_enum,
                                               "IDL:mtnm.tmforum.org/terminationPoint/Directionality_T:1.0",
                                               "Directionality_T",
                                               ["D_NA","D_BIDIRECTIONAL",
                                                "D_SOURCE","D_SINK"]}},
                                             {"transmissionParams",
                                              {tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/transmissionParameters/LayeredParameters_T:1.0",
                                                "LayeredParameters_T",
                                                [{"layer",tk_short},
                                                 {"transmissionParams",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                    "NameAndStringValue_T",
                                                    [{"name",{tk_string,0}},
                                                     {"value",{tk_string,0}}]},
                                                   0}}]},
                                               0}},
                                             {"tpProtectionAssociation",
                                              {tk_enum,
                                               "IDL:mtnm.tmforum.org/terminationPoint/TPProtectionAssociation_T:1.0",
                                               "TPProtectionAssociation_T",
                                               ["TPPA_NA",
                                                "TPPA_PSR_RELATED"]}},
                                             {"edgePoint",tk_boolean},
                                             {"additionalInfo",
                                              {tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                "NameAndStringValue_T",
                                                [{"name",{tk_string,0}},
                                                 {"value",{tk_string,0}}]},
                                               0}}]},
                                           0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:mtnm.tmforum.org/terminationPoint/TerminationPoint_T:1.0",
                                                "TerminationPoint_T",
                                                [{"name",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                    "NameAndStringValue_T",
                                                    [{"name",{tk_string,0}},
                                                     {"value",{tk_string,0}}]},
                                                   0}},
                                                 {"userLabel",{tk_string,0}},
                                                 {"nativeEMSName",
                                                  {tk_string,0}},
                                                 {"owner",{tk_string,0}},
                                                 {"ingressTrafficDescriptorName",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                    "NameAndStringValue_T",
                                                    [{"name",{tk_string,0}},
                                                     {"value",{tk_string,0}}]},
                                                   0}},
                                                 {"egressTrafficDescriptorName",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                    "NameAndStringValue_T",
                                                    [{"name",{tk_string,0}},
                                                     {"value",{tk_string,0}}]},
                                                   0}},
                                                 {"type",
                                                  {tk_enum,
                                                   "IDL:mtnm.tmforum.org/terminationPoint/TPType_T:1.0",
                                                   "TPType_T",
                                                   ["TPT_PTP","TPT_CTP",
                                                    "TPT_TPPool"]}},
                                                 {"connectionState",
                                                  {tk_enum,
                                                   "IDL:mtnm.tmforum.org/terminationPoint/TPConnectionState_T:1.0",
                                                   "TPConnectionState_T",
                                                   ["TPCS_NA",
                                                    "TPCS_SOURCE_CONNECTED",
                                                    "TPCS_SINK_CONNECTED",
                                                    "TPCS_BI_CONNECTED",
                                                    "TPCS_NOT_CONNECTED"]}},
                                                 {"tpMappingMode",
                                                  {tk_enum,
                                                   "IDL:mtnm.tmforum.org/terminationPoint/TerminationMode_T:1.0",
                                                   "TerminationMode_T",
                                                   ["TM_NA",
                                                    "TM_NEITHER_TERMINATED_NOR_AVAILABLE_FOR_MAPPING",
                                                    "TM_TERMINATED_AND_AVAILABLE_FOR_MAPPING"]}},
                                                 {"direction",
                                                  {tk_enum,
                                                   "IDL:mtnm.tmforum.org/terminationPoint/Directionality_T:1.0",
                                                   "Directionality_T",
                                                   ["D_NA","D_BIDIRECTIONAL",
                                                    "D_SOURCE","D_SINK"]}},
                                                 {"transmissionParams",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:mtnm.tmforum.org/transmissionParameters/LayeredParameters_T:1.0",
                                                    "LayeredParameters_T",
                                                    [{"layer",tk_short},
                                                     {"transmissionParams",
                                                      {tk_sequence,
                                                       {tk_struct,
                                                        "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                        "NameAndStringValue_T",
                                                        [{"name",
                                                          {tk_string,0}},
                                                         {"value",
                                                          {tk_string,0}}]},
                                                       0}}]},
                                                   0}},
                                                 {"tpProtectionAssociation",
                                                  {tk_enum,
                                                   "IDL:mtnm.tmforum.org/terminationPoint/TPProtectionAssociation_T:1.0",
                                                   "TPProtectionAssociation_T",
                                                   ["TPPA_NA",
                                                    "TPPA_PSR_RELATED"]}},
                                                 {"edgePoint",tk_boolean},
                                                 {"additionalInfo",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0",
                                                    "NameAndStringValue_T",
                                                    [{"name",{tk_string,0}},
                                                     {"value",{tk_string,0}}]},
                                                   0}}]},
                                               0}), mode='PARAM_OUT'}
, #parameterdescription{name="how_many", type=tk_ulong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:mtnm.tmforum.org/globaldefs/ProcessingFailureException:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_2, "IDL:mtnm.tmforum.org/terminationPoint/TerminationPointIterator_I/getLength:1.0", "getLength", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), 'OP_NORMAL', [], [orber_ifr:lookup_id(OE_IFR,"IDL:mtnm.tmforum.org/globaldefs/ProcessingFailureException:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_2, "IDL:mtnm.tmforum.org/terminationPoint/TerminationPointIterator_I/destroy:1.0", "destroy", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [], [orber_ifr:lookup_id(OE_IFR,"IDL:mtnm.tmforum.org/globaldefs/ProcessingFailureException:1.0")], []),

    ok.


%% General IFR registration checks.
register_tests(OE_IFR)->
  re_register_test(OE_IFR),
  include_reg_test(OE_IFR).


%% IFR type Re-registration checks.
re_register_test(OE_IFR)->
  case orber_ifr:'Repository_lookup_id'(OE_IFR,"IDL:mtnm.tmforum.org/terminationPoint/Directionality_T:1.0") of
    []  ->
      true;
    _ ->
      exit({allready_registered,"IDL:mtnm.tmforum.org/terminationPoint/Directionality_T:1.0"})
 end.


%% IFR registration checks for included idl files.
include_reg_test(OE_IFR) ->
  case orber_ifr:'Repository_lookup_id'(OE_IFR,"IDL:mtnm.tmforum.org/globaldefs:1.0") of
    [] ->
      exit({unregistered,"IDL:mtnm.tmforum.org/globaldefs:1.0"});
    _  ->
      true
  end,
  case orber_ifr:'Repository_lookup_id'(OE_IFR,"IDL:mtnm.tmforum.org/transmissionParameters:1.0") of
    [] ->
      exit({unregistered,"IDL:mtnm.tmforum.org/transmissionParameters:1.0"});
    _  ->
      true
  end,
  true.


%% Fetch top module reference, register if unregistered.
oe_get_top_module(OE_IFR, ID, Name, Version) ->
  case orber_ifr:'Repository_lookup_id'(OE_IFR, ID) of
    [] ->
      orber_ifr:'Repository_create_module'(OE_IFR, ID, Name, Version);
    Mod  ->
      Mod
   end.

%% Fetch module reference, register if unregistered.
oe_get_module(OE_IFR, OE_Parent, ID, Name, Version) ->
  case orber_ifr:'Repository_lookup_id'(OE_IFR, ID) of
    [] ->
      orber_ifr:'ModuleDef_create_module'(OE_Parent, ID, Name, Version);
    Mod  ->
      Mod
   end.



oe_unregister() ->
    OE_IFR = orber_ifr:find_repository(),

    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/terminationPoint/TerminationPointIterator_I:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/terminationPoint/TerminationPointList_T:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/terminationPoint/TerminationPoint_T:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/terminationPoint/TPProtectionAssociation_T:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/terminationPoint/TerminationMode_T:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/terminationPoint/TPType_T:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/terminationPoint/TPConnectionState_T:1.0"),
    oe_destroy(OE_IFR, "IDL:mtnm.tmforum.org/terminationPoint/Directionality_T:1.0"),
    oe_destroy_if_empty(OE_IFR, "IDL:mtnm.tmforum.org/terminationPoint:1.0"),
    ok.


oe_destroy_if_empty(OE_IFR,IFR_ID) ->
    case orber_ifr:'Repository_lookup_id'(OE_IFR, IFR_ID) of
	[] ->
	    ok;
	Ref ->
	    case orber_ifr:contents(Ref, 'dk_All', 'true') of
		[] ->
		    orber_ifr:destroy(Ref),
		    ok;
		_ ->
		    ok
	    end
    end.

oe_destroy(OE_IFR,IFR_ID) ->
    case orber_ifr:'Repository_lookup_id'(OE_IFR, IFR_ID) of
	[] ->
	    ok;
	Ref ->
	    orber_ifr:destroy(Ref),
	    ok
    end.



%% Idl file dependency list function
oe_dependency() ->

    {"d:/corba/idl/terminationPoint.idl",
     ["globaldefs.idl","transmissionParameters.idl"]}.

