%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: session_Session_I
%% Source: d:/corba/idl/session.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(SESSION_SESSION_I_HRL).
-define(SESSION_SESSION_I_HRL, true).




-endif.


